apiVersion: v1
kind: Service
metadata:
  name: test-deployment-01-service
spec:
  type: NodePort
  selector:
    app: test-nginx
  ports:
    - port: 80          
      targetPort: 80     
      nodePort: 30080    
